#define OPEN_INTERFACE_ARM "OPEN_INTERFACE"
#define SPIN_INTERFACE_ARM "SPIN_INTERFACE"
#define CLOSE_INTERFACE_ARM "CLOSE_INTERFACE"

#define OPEN_GRIPPER_ARM "OPEN_GRIPPER"
#define TOGGLE_GRIPPER_ARM "TOGGLE_GRIPPER"
#define CLOSE_GRIPPER_ARM "CLOSE_GRIPPER"

#define TOGGLE_UTILITY_ARM_1 "TOGGLE_UTILITY_1"
#define TOGGLE_UTILITY_ARM_2 "TOGGLE_UTILITY_2"